const icons = [
    'logo',
    'select-arrow',
    'search',
    'menu-open',
    'menu-close',
    'cookies-close',
    'popup-close',
    'scan',
    'faq-drop',
    'check',
    'upload',
    'next-arrow',
    'prev-arrow',
    'menu-item',
    'map-arrow',
    'arrow-prev-short',
    'arrow-next-short',
    'arrow-next-long',
    'arrow-prev-long',
    'arrow-card-next',
    'arrow-next-thin',
    'arrow-prev-thin',
    'copy',
    'download',
    'info-i',
    '5ka-back-arrow',
    '5ka-card-arrow',
    'attachment',
] as const;

export default icons;
